### ISSUE TITLE
How to use docker_auth server with plain http instead of https

### ISSUE THREAD

**Issue by ashishjain14** [cesanta/docker_auth#130]
The link https://github.com/cesanta/docker_auth/blob/master/examples/reference.yml#L15 here says that if you do not specify certificate and key it will open a plain http listener. But once I remove these 2 variables or else keep them blank, I see docker_auth server complaining about missing certificate and key. Is this a bug? Moreover how I can start the auth server with plain http?

**Comment by rojer** [comment]
in that same line it also says: "In that case token.certificate and key must be provided."

**Comment by ashishjain14** [comment]
thank you it helped, the issue is resolved.

**Comment by SantoDE** [comment]
I fail to create that correctly. Why do I need to set token.certificate and key, if it's really all about plain HTTP? I have a loadbalancer sitting in front of the auth server which does all the SSL termination for me. How do I need to set that both settings in order to really have plain http up? Mayve @rojer or @ashishjain14 ?

**Comment by rojer** [comment]
@SantoDE a cert is required wither way, because token must be signed by a key/cert that registry trusts (to which a chain of trust can be built from one of the certs in auth.token.rootcertbundle). normally it's the same cert that is used for https, but if you use plain http and do not specify cert/key for it, `token.certificate` and `key` MUST be set. i don't know why it's so difficult to understand, really.

**Comment by SantoDE** [comment]
Ah, so this is required by the protocol. Okay. Then i need to find a way how to use this behind my load Balancer which fetches it's certs by letsencrypt :/

**Comment by rojer** [comment]
this is strictly between registry and auth server, you can use a single self-signed cert here.
put it in auth server's token.cert/key and registry's auth.token.rootcertbundle

**Comment by SantoDE** [comment]
Ah cool! Thanks a lot then. Thats easy :)
