### ISSUE TITLE
A Question about Code

### ISSUE THREAD

**Issue by onlyellow** [cesanta/docker_auth#134]
The func NewMongoAuth (in the mongo_auth.go), it use the copy of session: tmp_session like below:

`   // Copy our session

```
tmp_session := session.Copy()
// Close up when we are done
defer tmp_session.Close()
// determine collection
collection := tmp_session.DB(c.MongoConfig.DialInfo.Database).C(c.Collection)`
```

Is it benefit for using copy? Why not use origin session directly?

Thanks

**Comment by rojer** [comment]
@carsonoid should know

**Comment by carsonoid** [comment]
@onlyellow I primarily did it because all of the docs I read recommended it. I'm not an expert but from what I've read if you don't copy the session than all the go routines using the main session have to share a socket which can cause one routine to wait for the other to finish. Since it's possible for many auths be happening at the same time it's much safer to give each authentication it's own session.
