### ISSUE TITLE
Rename generic "auth_server" binary

### ISSUE THREAD

**Issue by mrueg** [cesanta/docker_auth#163]
If you build this project currently the resulting binary is called auth_server. This is rather generic and doesn't connect it to docker.

I would suggest renaming it to something that includes "docker" or "registry" so people can connect the binary with docker/registry. Maybe registry_auth instead?

**Comment by rojer** [comment]
you have a point, but it's a rather minor one. main way people use this is via Docker container called `cesanta/docker_auth` which is more specific. perhaps i should've called it `docker_auth_server`, but that train has sailed ;)

**Comment by thias** [comment]
@mrueg : I sort of agree, but keep in mind that you can rename the resulting binary to anything you like. For instance, I have created an rpm package and called all of the package, the binary and the service `docker-distribution-auth` in order to integrate nicely with the `docker-distribution` package that Red Hat provides : http://git.marmotte.net/git/rpms/tree/redhat/7Server/docker-distribution-auth

Docker's own "registry", "registry v2" and "distribution" naming is quite confusing IMHO, and I personally wish they hadn't gone with the "distribution" name for what everyone keeps calling a "registry" in the first place... Also, Docker Inc has been known to go after 3rd parties using the "Docker" brand, so keeping `auth_server` is probably safer than renaming to `docker_auth_server`, see https://github.com/docker/docker/issues/26556 for some details.
