### ISSUE TITLE
UI / Admin Interface

### ISSUE THREAD

**Issue by DirkHeinke** [cesanta/docker_auth#2]
Hi,
cool you build this, great work! Do you plan to add a admin panel, or CLI for creating users and controlling access?

**Comment by rojer** [comment]
i agree that having static list of users is not ideal, but maintaining a separate user database is also something i'd like to avoid.
since the organization where this server will be deployed probably already has some sort of account database (for us it's google apps, for others it may be a windows domain or kerberos realm), i think the way to go is to provide integration with those, plus static accounts for automated systems.

**Comment by summerQLin** [comment]
Do you have plan to integrate LDAP systems?

**Comment by rojer** [comment]
this is something that makes sense to me and i would welcome as a contribution, but cannot promise myself as working on docker_auth is not my main priority.

**Comment by DarkDirk** [comment]
I build [this webinterface](https://github.com/DarkDirk/docker_auth_web) to access the config. But it needs #6 for working seamless.

**Comment by rojer** [comment]
i'm on board with config reload, but a ui to edit config file seems out of
place to me.
i think the need to have dynamic set of users/permissions is best addressed
through dynamic backends (as suggested in another issue).

**Comment by rojer** [comment]
config reload was implemented in #13 , i do not plan to implement a UI (beyond the bare minimum necessary for e.g. google or github auth - you can judge my [lack of] UI skills by that :)).
