### ISSUE TITLE
the `/tmp` directory

### ISSUE THREAD

**Issue by fxdgear** [cesanta/docker_auth#241]
The auth service writes lots to a `/tmp` directory. 

1. Why?
2. Why is this not documented
3. This directory will grow and grow as the service runs consuming disk space making it difficult to track down since it's inside the container. 

Currently we have to volume mount `/authlogs:/tmp` when running the process so we can prune these log files. 

Using any cli flags when starting the process doesn't limit the creation of these log files: 

```
auth_server.5fe4bb4505db.unknownuser.log.INFO.20180727-181500.1
```

**Comment by carsonoid** [comment]
This is a function of the `glog` library that is used in the server: https://github.com/golang/glog

According to the source code you should be able to use the `-logtostderr=true -alsologtostderr=false` flags to only log to sderr instead of files.

Note: You don't technically need to set the `-alsologtostderr` flag since the default is `false` but I put it here for explicitness.

**Comment by fxdgear** [comment]
ALSO, why is this file a binary file? When i attempt to `less` the file i get the following: 

```
"auth_server.5fe4bb4505db.unknownuser.log.INFO.20180727-181500.1" may be a binary file. See it anyway?
```

Though `cat`ing the file seems to work just fine. Attemping to parse these logs using logstash/filebeat fails because I end up with a wall of `/u0000` and I think there's something going on with the way either `docker_auth` is writing the log files and or the way `glog` is being used. 

I'm not a go dev unfortunately so knowing where or how or why by looking at the code is not in my wheelhouse.

**Comment by fxdgear** [comment]
closing, thanks for the response. sorry for the noise
