### ISSUE TITLE
OpenID Connect Support?

### ISSUE THREAD

**Issue by nynymike** [cesanta/docker_auth#47]
You have Google authentication, and with just a little more work, you could support [OpenID Connect](http://openid.net/connect). Google's server is [almost compliant](http://openid.net/certification)--they don't support dynamic client registration. I bet a lot of companies that use Docker don't want to rely on a central consumer IDP like Google, but would rather run their own authentication service with something more modern than LDAP (which is limited to username / password). My company makes a fully compliant free open source OpenID Connect Provider that is [easy to deploy](http://www.gluu.org/docs/admin-guide/deployment/) called the [Gluu Server](http://gluu.org). We don't program Go, but we'd be happy to help you if you have any questions about how to setup a test server. Although it is ridiculously easy--apt-get install and run a setup program...

**Comment by rojer** [comment]
docker_auth is a side project for us (me). Google auth is there only because we use it, and LDAP is there only because other people were interested.
but yeah, what you're saying makes sense. however, it will have to wait until someone comes along to implement it or i have spare time.

to anyone reading this: feel free to take it on and generalize google auth to open id and send me a PR.

**Comment by FBasels** [comment]
Merged with #307
