### ISSUE TITLE
mongo acl update fails on primary re-election of mongo replica set

### ISSUE THREAD

**Issue by mv012004** [cesanta/docker_auth#71]
We are facing a strange issue when the primary mongo instance from the mongo cluster goes down, the auth server throws the following error in the logs,

```
tail -f /var/lib/docker/containers/77a26e18a502696d9da77afb39603a24aae4a936cb1b02268582cb7d3c3bcc50/77a26e18a502696d9da77afb39603a24aae4a936cb1b02268582cb7d3c3bcc50-json.log
{"log":"E0309 16:39:37.399743      1 acl_mongo.go:138] Failed to update ACL. ERROR: EOF\n","stream":"stderr","time":"2016-03-09T16:39:37.400394964Z"}
{"log":"W0309 16:39:37.400356      1 acl_mongo.go:139] Using stale ACL (Age: 1m59.99889041s, TTL: 1m0s)\n","stream":"stderr","time":"2016-03-09T16:39:37.400888752Z"}
{"log":"E0309 16:40:37.399780      1 acl_mongo.go:138] Failed to update ACL. ERROR: EOF\n","stream":"stderr","time":"2016-03-09T16:40:37.400130687Z"}
{"log":"W0309 16:40:37.400094      1 acl_mongo.go:139] Using stale ACL (Age: 2m59.998905529s, TTL: 1m0s)\n","stream":"stderr","time":"2016-03-09T16:40:37.400527491Z"}
```

Once the config file is changed (i just did an `echo " ">> /config/ldap_auth.yml`) and it reloaded the config and it starts working

```
{"log":"I0309 16:41:09.447069      1 main.go:144] Restarting server\n","stream":"stderr","time":"2016-03-09T16:41:09.450893014Z"}
{"log":"I0309 16:41:09.448508      1 main.go:150] New config loaded\n","stream":"stderr","time":"2016-03-09T16:41:09.450938039Z"}
{"log":"I0309 16:41:09.448611      1 server.go:283] Server stopped\n","stream":"stderr","time":"2016-03-09T16:41:09.45094872Z"}
{"log":"I0309 16:41:09.448622      1 main.go:43] Config from /config/ldap_auth.yml (1 users, 2 ACL static entries)\n","stream":"stderr","time":"2016-03-09T16:41:09.45095705Z"}
{"log":"W0309 16:41:09.458879      1 main.go:78] Running without TLS\n","stream":"stderr","time":"2016-03-09T16:41:09.459429096Z"}
{"log":"I0309 16:41:09.459040      1 main.go:90] Serving\n","stream":"stderr","time":"2016-03-09T16:41:09.459466899Z"}
```

Has anyone seen a similar issue and is there a better workaround/fix for setting the read preference for the replica set.?

**Comment by carsonoid** [comment]
First off, you should update  your auth_server. Judging by the line numbers
in the errors you are running an old version.  The new version will most
likely handle this correctly.

---

However when it comes to authentication with mongo we should implement a
fix so that we automatically retry when we get EOF errors.

There is a long discussion about this here:
https://github.com/go-mgo/mgo/issues/49

New versions of docker_auth are already doing a session.Copy() for each
transaction.  It looks like we simply need to retry the transaction when we
get an EOF as the error. The driver should have already updated to use the
new server address and when we copy the session again it should work.

My understanding of the process based on my research:

   1. mongo failover happens
   2. auth_server attempts mongo transaction and get's EOF.
      - At this point the mgo driver automatically reconnects. Any new
      sessions created with Copy() should succeed and use the new server
   3. auth_server should see the EOF error and retry it's transactions.

All that really needs to happen is for number 3 to be implemented in the
functions that catch mongo errors.

**Comment by mv012004** [comment]
Thanks @carsonoid let me quickly try this, will keep you posted.

**Comment by mv012004** [comment]
Thanks for pointing us to the new version @carsonoid 
The issue still persisted with the new version, but as a temp fix, we created a crontab which parses the log every minute and creates a field in the yml file (errorCount) and updates the value so that the main.go reloads the config and the mongo config refreshes.

**cache_ttl issue

We observed that when the cache_ttl timeout is reached and the AUTH server refreshes the cache, the incoming request for push fails, have you observed this behavior ?

Thanks,
Mihir

**Comment by rojer** [comment]
built and pushed to `:latest`
